name: CI
on: [push, pull_request]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Haskell
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: 8.8.4
          enable-stack: true
          stack-version: 2.5.1
      - name: Run tests
        run: stack test
